@startuml
object "lion1: Lion" as lion1 {
  nom = "Simba"
  age = 5
  poids = 190.5
  taille = 1.2
  etatDeSante = "Bon"
}

object "savane1: Savane" as savane1 {
  nom = "Savane Africaine"
  taille = 1000.0
  temperature = 28.5
}

object "soigneur1: SoigneurImpl" as soigneur1 {
  nom = "Jean Dupont"
  poste = "Soigneur principal"
  salaire = 2500.0
}

object "visiteur1: Visiteur" as visiteur1 {
  nom = "Marie Martin"
  age = 30
  billet = "Adulte"
}

savane1 -- lion1 : contient >
soigneur1 -- lion1 : soigne >
visiteur1 -- lion1 : observe >
@enduml 