@startuml
left to right direction
skinparam packageStyle rectangle

actor Soigneur
actor Veterinaire
actor Visiteur
actor Directeur

rectangle "Réserve Naturelle" {
  usecase "Nourrir les animaux" as UC1
  usecase "Soigner les animaux" as UC2
  usecase "Nettoyer les habitats" as UC3
  usecase "Observer les animaux" as UC4
  usecase "Acheter un billet" as UC5
  usecase "Gérer le personnel" as UC6
  usecase "Superviser la reproduction" as UC7
  usecase "Effectuer des examens médicaux" as UC8
  usecase "Gérer les stocks" as UC9
}

Soigneur --> UC1
Soigneur --> UC3
Soigneur --> UC7

Veterinaire --> UC2
Veterinaire --> UC8

Visiteur --> UC4
Visiteur --> UC5

Directeur --> UC6
Directeur --> UC9
@enduml 